[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "errorlog"
NIXPACKS_PHP_ROOT_DIR = "/app/public"