[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "errorlog"

[nixpacks]
cmds = ["php artisan config:cache", "php artisan route:cache"]